spring:
  profiles:
    active: dev
  application:
    name: Globetrek platform api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/globetrek_platform
    username: root
    password: 090804
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    user:
      name: dungtv
      password: HptKLumNSqLqgF
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            # project_id: elearning-platform-api
            # auth_uri: https://accounts.google.com/o/oauth2/auth
            # token_uri: https://oauth2.googleapis.com/token
            # auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: globetrek2x@gmail.com
    password: "..."
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  refresh_token_expiration_time: 5184000 #60 days = 60 * 24 * 60 * 60
  token_expiration_time: 2592000 # 30 days = 30 * 24 * 60 * 60
  secretkey: UajeM9pNkWoC8mSXkiltuYgSqi1/iqmp3jIXyseYdmcci++kXR8g4XFg3p9tiTCO

api:
  prefix: /api/v1

openapi:
  title: Globetrek platform API document
  version: v1.0.0
  description: API system service for globetrek application
  server:
    description: localhost-dungtv2x
  contact:
    email: dungtv2x@gmail.com




